server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.61.190:8761/eureka

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
#          uri: http://192.168.61.190:8081/
#          predicates:
#            - Path=/first-service/**
#        - id: second-service
#          uri : http://192.168.61.190:8082/
#          predicates:
#            - Path=/second-service/**